### ISSUE TITLE
Nie wyświetlają się numery stron

### ISSUE THREAD

**Issue by wesolyfoton** [wesolyfoton/aisd-skrypt#26]
I nie mam pojęcia dlaczego.

**Comment by Bozydarek** [comment]
Numery nie pojawiają się na tych stronach które pochądzą z dołączonych plików, a są np. na stronach z rozdziałami.

**Comment by Bozydarek** [comment]
Cofnąłem się kilka razy wstecz i z tego co widzę to problem był od zawsze. Ale co ciekawe czasem numery pojawiają się w plikach dołączonych. Np w 15d36db86b1b60f9b64f1583adb561c9bd1b06ea pojawia się numer 7 w pliku `kopiec.tex`, ale na kolejnej stronie - również z tego pliku - już numeru nie ma :/

**Comment by Bozydarek** [comment]
Ok, udało mi się "pojawić" numerki, ale w zaskakującym dla mnie miejscu. Na stronach powstałych z głównego pliku, np. przez wstawienie:
```TeX 
\tableofcontents
\chapter{ }
```
Numeracja jest na dole strony - wyśrodkowana.

Natomiast na stronach z 
```TeX 
\include{ }
```
Numeracja jest na górze strony, dodatkowo odpowiednio po lewej lub prawej (jak w książce).

Plus ciekawostka: Pierwsza strona również jest ponumerowana, ale druga i czwarta nie mają na sobie nic (tak jak wcześniej).

Nie wiem czy to jest akceptowalne rozwiązanie.

**Comment by Bozydarek** [comment]
Dobra, mam wszystkie numerki wyśrodkowane i na dole stron. W tym że jest parę stron całkowicie pustych (bez numeru ani treści), ale uwzględnionych w numeracji. Plus mam też numer na pierwszej i ostatniej stronie.

**Comment by Bozydarek** [comment]
Usunąłem numery z pierwszej i ostatniej strony (na ostatniej numer był pod tabelką z "ptaszkami" , więc brzydko to wyglądało) i rozumiem co się stało. 

Problem leżał w linijce 119 (https://github.com/wesolyfoton/aisd-skrypt/blob/master/skrypt.tex#L119).
```TeX
\pagestyle{empty}
```
Niestety nigdzie potem nie było użyte
```TeX
\pagestyle{plain}
```
Zatem, jeśli ktoś z jakiegoś powodu chce usunąć numerację na jakiejś stronie musi pamiętać, żeby ją przywrócić dodając później `\pagestyle{plain}`. Nie rozumiem natomiast czemu czasem numery jednak się pojawiały. Tu mogę tylko zgadywać.

Rozwiązałem również zagadkę pustych stron, ale nie umiem rozwiązać ich problemu. Otóż po każdym wstawieniu rozdziału jeśli znajduje się on na parzystej stronie to jest on przesuwany na nieparzystą, a w jego miejsce jest wstawiana nie numerowana pusta strona. Dokładanie tak jak powinno być w książce. Nie wiem czy będziemy z tym walczyć, czy może zmienimy styl całego dokumentu na "książkowy" - tzn. numeracja odpowiednio (prawa/lewa) itd.

**Comment by Bozydarek** [comment]
Na moim forku dodałem gałąź z podglądem - jakby to wyglądało - Bozydarek@313bbebdb28593ccf023175941021c75db7964c1.
Dodatkowym bonusem tego rozwiązanie jest nagłówek z numerem i nazwą działu :)

**Comment by wesolyfoton** [comment]
Super że się tym zająłeś. Też mi się wydaje, że te parzyste/nieparzyste wynikają z tego, że styl dokumentu to "książka". Wolałbym aby puste strony pojawiały się być może po każdej części a nie po rozdziale, ale tym mozna zająć się dużo później.
