### ISSUE TITLE
Algorytm Boruvki jest w złej sekcji

### ISSUE THREAD

**Issue by Tomatosoup97** [wesolyfoton/aisd-skrypt#53]
Algorytm Boruvki został już zmerge'owany, aczkolwiek wciąż jest w sekcji "Nie zaczęte". Powinien zostać przeniesiony do "W toku" / "Zrobione", zarówno w README jak i w `skrypt.tex`.

**Comment by wesolyfoton** [comment]
Proszę się tym nie przejmować.
