### ISSUE TITLE
Niepoprawna numeracja w Algorytmie Dijkstry

### ISSUE THREAD

**Issue by Tomatosoup97** [wesolyfoton/aisd-skrypt#54]
Coś zostało skopane. 

Jest:
- 2.6 Algorytm Dijkstry
- 2.7 Dowód poprawności algorytmu
- 2.8 Analiza

Powinno być:
- 2.6 Algorytm Dijkstry
- 2.6.1 Dowód poprawności algorytmu
- 2.6.2 Analiza

**Comment by wesolyfoton** [comment]
Sekcje w ogóle nie powinny mieć subsekcji.

**Comment by Tomatosoup97** [comment]
Rozwiązane przez commit od @Bozydarek
